spring.application.name=smart-hire-ai

ollama.api.url=http://localhost:11434/api/generate
ollama.model=llama3.2:1b

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB